# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_MYPY
  - PYTHON_FLAKE8
  - PYTHON_PYRIGHT
  - PYTHON_ISORT

DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

GITHUB_COMMENT_REPORTER: false

PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_BLACK_DISABLE_ERRORS: false
PYTHON_FLAKE8_CONFIG_FILE: .flake8
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_DISABLE_ERRORS: false
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_PYRIGHT_CONFIG_FILE: pyproject.toml

SHOW_ELAPSED_TIME: true
